ENG-12957: Add section for S3 File Browser configuration
cyral-quickstart/quickstart-sidecar-helm pull request #7
Opened 2024-03-08 18:39 UTC by VictorGFM

2024-03-11 19:15 UTC, wcmjunior requested changes
Same observation is the other PRs: this new section should live on a separate `docs` page referred from the `Advanced` section of the main README.

2024-03-12 16:19 UTC, VictorGFM commented on README.md
> +  dnsName: "<CNAME>" # ex: "www.sidecar-custom-name.com"
Addressed: [Move s3 documentation to /docs directory](https://github.com/cyral-quickstart/quickstart-sidecar-helm/pull/7/commits/e3ec5608d65fde017d3456b118e7c4d3a56e1f71)

2024-03-12 16:42 UTC, wcmjunior commented on README.md
> +* [Enable the S3 File Browser](./docs/s3-browser.md)
Please keep the items in alphabetical order.

2024-03-12 16:42 UTC, wcmjunior commented on docs/s3-browser.md
> +sidecar](https://cyral.com/docs/sidecars/manage/alias).
```suggestion
The CNAME provided in `service.dnsName` must be created
after the deployment pointing to the sidecar load balancer.
See [Add a CNAME or A record for the sidecar](https://cyral.com/docs/sidecars/manage/alias).
```

2024-03-12 17:37 UTC, wcmjunior approved these changes

2024-03-12 17:37 UTC, merged